version: "3"

services:
  app:
    build:
      context: ./
    container_name: ${APP_NAME}_app
    volumes:
      - ./:/usr/app:rw
      - /usr/app/vendor
    networks:
      frontend:
        ipv4_address: ${F_APP_HOST}
      backend:
        ipv4_address: ${B_APP_HOST}

  nginx:
    image: nginx:1.15-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "${APP_PORT}:80"
      - "${APP_SSL_PORT}:443"
    volumes:
      - ./:/usr/app
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      frontend:
        ipv4_address: ${F_NGINX_HOST}

  mysql:
    image: mysql
    container_name: ${APP_NAME}_mysql
    restart: always
    ports:
      - ${DB_LOCAL_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      backend:
        ipv4_address: ${DB_HOST}

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: ${F_SUBNET}
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: ${B_SUBNET}
